name: Go

on:
  push:
    branches: [ "main" ]

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    outputs:
      next_version: ${{ steps.version.outputs.next_version }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Required to fetch all tags

    - name: Determine next version
      id: version
      run: |
        git fetch --tags
        latest_tag=$(git tag | sort -V | tail -n 1)
        next_version=$(echo $latest_tag | awk -F. '{$NF++;print}' OFS='.')
        echo "::set-output name=next_version::$next_version"

    - name: Create and push git tag
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git tag ${{ steps.version.outputs.next_version }}
        git push origin ${{ steps.version.outputs.next_version }}

  build:
    needs: prepare-release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: 386
          - goos: linux
            goarch: arm
          - goos: linux
            goarch: arm64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          - goos: windows
            goarch: amd64
          - goos: windows
            goarch: 386
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
        export GOOS=${{ matrix.goos }}
        export GOARCH=${{ matrix.goarch }}
        go build -v -o monkey-${{ matrix.goos }}-${{ matrix.goarch }} main.go

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: monkey-binaries
        path: ./monkey-*

  release:
    needs: [prepare-release, build]
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v2
      with:
        name: monkey-binaries

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./monkey-*
        tag_name: ${{ needs.prepare-release.outputs.next_version }}
        name: "Release ${{ needs.prepare-release.outputs.next_version }}"
        body: "Automated release for version ${{ needs.prepare-release.outputs.next_version }}"
        token: ${{ secrets.GITHUB_TOKEN }}
